server:
 port: 8080
spring:
 datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://3.112.49.158:3306/club?useUnicode=true&characterEncoding=utf-8
  username: root
  password: root
 devtools:
   livereload:
    enabled: true
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   # ddl-auto: create
 thymeleaf:
  prefix: classpath:templates/
  suffix: .html
  cache: false
  check-template-location: true
jwt:
 secretKey: "test123"


