server:
 port: 8280
spring:
 datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://3.112.49.158:3306/CLUB?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 1234
 devtools:
   livereload:
    enabled: true
 jpa:
  show-sql: true
  hibernate:
#   ddl-auto: update
   ddl-auto: create-drop
 thymeleaf:
  cache: false
jwt:
 secretKey: "test123"


