server:
 port: 8080
spring:
 datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://3.112.49.158:3306/club?useUnicode=true&characterEncoding=utf-8
  username: root
  password: root
 devtools:
   livereload:
    enabled: true
 jpa:
  properties:
   hibernate:
    show_sql: true
    format_sql: true
    use_sql_comments: true
    ddl-auto: update
   # ddl-auto: create
 thymeleaf:
  prefix: classpath:templates/
  suffix: .html
  cache: false
  check-template-location: true
logging:
 level:
  org:
   hibernate:
    type:
     descriptor:
      #sql: trace #sql 파라미터 확인
jwt:
 secretKey: "test123"


