server:
 port: 8280
spring:
 datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://3.112.33.192:3306/CLUB?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 1234
 jpa:
  show:
    sql: true